# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hsakamot <hsakamot@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/09 21:17:24 by hsakamot          #+#    #+#              #
#    Updated: 2021/03/09 21:17:27 by hsakamot         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ft_hexdump: ft_hexdump.c ft_puterror.c
	gcc -Wall -Wextra -Werror $^ -o ft_hexdump

all:	ft_hexdump

clean:

fclean:
	rm -f ft_hexdump
